project_id = "lgxqviomumjiqljpnvuh"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true

[studio]
enabled = true
port = 54324

[inbucket]
enabled = true
port = 54325
smtp_port = 54326
pop3_port = 54327

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "https://localhost:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = false
enable_confirmations = false

[auth.sms]
enable_signup = false
enable_confirmations = false

[analytics]
enabled = false

[functions.azure-openai-chat]
verify_jwt = false

[functions.azure-speech-transcribe]
verify_jwt = false

[functions.project-management]
verify_jwt = false

[functions.transcript-analysis]
verify_jwt = false

[functions.enhanced-transcript-processing]
verify_jwt = false

[functions.content-analysis-queue]
verify_jwt = false

[functions.content-analysis-worker]
verify_jwt = false